/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemindersIndexRouteImport } from './routes/reminders/index'
import { Route as RemindersNewIndexRouteImport } from './routes/reminders/new/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIndexRoute = RemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersNewIndexRoute = RemindersNewIndexRouteImport.update({
  id: '/reminders/new/',
  path: '/reminders/new/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reminders/': typeof RemindersIndexRoute
  '/reminders/new/': typeof RemindersNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reminders': typeof RemindersIndexRoute
  '/reminders/new': typeof RemindersNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reminders/': typeof RemindersIndexRoute
  '/reminders/new/': typeof RemindersNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reminders/' | '/reminders/new/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reminders' | '/reminders/new'
  id: '__root__' | '/' | '/reminders/' | '/reminders/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RemindersIndexRoute: typeof RemindersIndexRoute
  RemindersNewIndexRoute: typeof RemindersNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/': {
      id: '/reminders/'
      path: '/reminders'
      fullPath: '/reminders/'
      preLoaderRoute: typeof RemindersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/new/': {
      id: '/reminders/new/'
      path: '/reminders/new'
      fullPath: '/reminders/new/'
      preLoaderRoute: typeof RemindersNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RemindersIndexRoute: RemindersIndexRoute,
  RemindersNewIndexRoute: RemindersNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
