/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RemindersIndexRouteImport } from './routes/reminders/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SettingsModesIndexRouteImport } from './routes/settings/modes/index'
import { Route as SettingsIntegrationsIndexRouteImport } from './routes/settings/integrations/index'
import { Route as SettingsAlertsIndexRouteImport } from './routes/settings/alerts/index'
import { Route as RemindersNewIndexRouteImport } from './routes/reminders/new/index'
import { Route as RemindersIdEditIndexRouteImport } from './routes/reminders/$id/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIndexRoute = RemindersIndexRouteImport.update({
  id: '/reminders/',
  path: '/reminders/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsModesIndexRoute = SettingsModesIndexRouteImport.update({
  id: '/settings/modes/',
  path: '/settings/modes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsIndexRoute =
  SettingsIntegrationsIndexRouteImport.update({
    id: '/settings/integrations/',
    path: '/settings/integrations/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsAlertsIndexRoute = SettingsAlertsIndexRouteImport.update({
  id: '/settings/alerts/',
  path: '/settings/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersNewIndexRoute = RemindersNewIndexRouteImport.update({
  id: '/reminders/new/',
  path: '/reminders/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersIdEditIndexRoute = RemindersIdEditIndexRouteImport.update({
  id: '/reminders/$id/edit/',
  path: '/reminders/$id/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reminders/': typeof RemindersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/reminders/new/': typeof RemindersNewIndexRoute
  '/settings/alerts/': typeof SettingsAlertsIndexRoute
  '/settings/integrations/': typeof SettingsIntegrationsIndexRoute
  '/settings/modes/': typeof SettingsModesIndexRoute
  '/reminders/$id/edit/': typeof RemindersIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/reminders': typeof RemindersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/reminders/new': typeof RemindersNewIndexRoute
  '/settings/alerts': typeof SettingsAlertsIndexRoute
  '/settings/integrations': typeof SettingsIntegrationsIndexRoute
  '/settings/modes': typeof SettingsModesIndexRoute
  '/reminders/$id/edit': typeof RemindersIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/reminders/': typeof RemindersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/reminders/new/': typeof RemindersNewIndexRoute
  '/settings/alerts/': typeof SettingsAlertsIndexRoute
  '/settings/integrations/': typeof SettingsIntegrationsIndexRoute
  '/settings/modes/': typeof SettingsModesIndexRoute
  '/reminders/$id/edit/': typeof RemindersIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/login/'
    | '/reminders/'
    | '/settings/'
    | '/reminders/new/'
    | '/settings/alerts/'
    | '/settings/integrations/'
    | '/settings/modes/'
    | '/reminders/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reminders'
    | '/settings'
    | '/reminders/new'
    | '/settings/alerts'
    | '/settings/integrations'
    | '/settings/modes'
    | '/reminders/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/login/'
    | '/reminders/'
    | '/settings/'
    | '/reminders/new/'
    | '/settings/alerts/'
    | '/settings/integrations/'
    | '/settings/modes/'
    | '/reminders/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RemindersIndexRoute: typeof RemindersIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  RemindersNewIndexRoute: typeof RemindersNewIndexRoute
  SettingsAlertsIndexRoute: typeof SettingsAlertsIndexRoute
  SettingsIntegrationsIndexRoute: typeof SettingsIntegrationsIndexRoute
  SettingsModesIndexRoute: typeof SettingsModesIndexRoute
  RemindersIdEditIndexRoute: typeof RemindersIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/': {
      id: '/reminders/'
      path: '/reminders'
      fullPath: '/reminders/'
      preLoaderRoute: typeof RemindersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/modes/': {
      id: '/settings/modes/'
      path: '/settings/modes'
      fullPath: '/settings/modes/'
      preLoaderRoute: typeof SettingsModesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations/': {
      id: '/settings/integrations/'
      path: '/settings/integrations'
      fullPath: '/settings/integrations/'
      preLoaderRoute: typeof SettingsIntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/alerts/': {
      id: '/settings/alerts/'
      path: '/settings/alerts'
      fullPath: '/settings/alerts/'
      preLoaderRoute: typeof SettingsAlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/new/': {
      id: '/reminders/new/'
      path: '/reminders/new'
      fullPath: '/reminders/new/'
      preLoaderRoute: typeof RemindersNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders/$id/edit/': {
      id: '/reminders/$id/edit/'
      path: '/reminders/$id/edit'
      fullPath: '/reminders/$id/edit/'
      preLoaderRoute: typeof RemindersIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RemindersIndexRoute: RemindersIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  RemindersNewIndexRoute: RemindersNewIndexRoute,
  SettingsAlertsIndexRoute: SettingsAlertsIndexRoute,
  SettingsIntegrationsIndexRoute: SettingsIntegrationsIndexRoute,
  SettingsModesIndexRoute: SettingsModesIndexRoute,
  RemindersIdEditIndexRoute: RemindersIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
